### ISSUE TITLE
What does the mask parameter refer to?

### ISSUE THREAD

**Issue by Wang-Shuo** [libuyu/GHM_Detection#2]
https://github.com/libuyu/GHM_Detection/blob/ff58c3e7643bcfc8dfb049d0d3e6c2f1da04f1a3/mmdetection/mmdet/core/loss/ghm_loss.py#L24

**Comment by libuyu** [comment]
Some of the candidate boxes are ignored for training such as crowded boxes in COCO. And the mask here means whether this candidate box is used (mask[i,j]=1) or ignored (mask[i,j]=0). It just acts as loss weights.

**Comment by Wang-Shuo** [comment]
I see. Thanks a lot.

**Comment by milliema** [comment]
May I ask where is the mask (now named as label_weight) calculated?
