### ISSUE TITLE
mutil-gpu train error

### ISSUE THREAD

**Issue by cxfwdz** [libuyu/GHM_Detection#23]
no distribution multi-gpu train exists error in the code:
"inds = (g<= edges[i])&(g<edges[i+1])&vaild"

the error is 
"arguments are located on different gpus at /pytorch/aten/THC/generic/THCTensorMathCompareT.cu:31"

**Comment by libuyu** [comment]
It seems the problem happens when data synchronizing. But sorry that I have never met with this error. I suggest that you open an issue under the  [mmdetection](https://github.com/open-mmlab/mmdetection/issues) repo since my code is based on it.

**Comment by cxfwdz** [comment]
> It seems the problem happens when data synchronizing. But sorry that I have never met with this error. I suggest that you open an issue under the [mmdetection](https://github.com/open-mmlab/mmdetection/issues) repo since my code is based on it.

**Comment by cxfwdz** [comment]
ok，thanks
