### ISSUE TITLE
What is the label_weight in GHM loss?

### ISSUE THREAD

**Issue by milliema** [libuyu/GHM_Detection#26]
Thanks for the work. I am planning to reuse GHM loss in other models, and I find that the label_weight matrix is required to compute ghmc and ghmr. In the code it mentions that if the sample is ignored then the value should be zero. How to compute the label_weight? In what situation should we ignore the sample?

**Comment by milliema** [comment]
I found the answer in other related issue,  #2 and #11 .

**Comment by immarioo** [comment]
hi, i saw the answer in issue [#17 ](https://github.com/libuyu/GHM_Detection/issues/17). "If there is no region to ignore, your mask should be 1 everywhere." so the label_weight set 1, am i correct?
BTW, have you got better results compared to focal loss and smooth l1 loss?
