### ISSUE TITLE
Accelerate for loop in GHM Loss

### ISSUE THREAD

**Issue by ZwwWayne** [libuyu/GHM_Detection#7]
It seems that the for loop in GHMLoss makes it kind of slow, could this be accelerated by torch.jit or something else?

**Comment by libuyu** [comment]
I think just using GPU parallel computing instead of the for loop can solve the problem. We already have a GPU version of Focal Loss, and the GPU version of GHM is upcoming. We will consider to release both of them if done.

**Comment by ZwwWayne** [comment]
Wow, good job!! I am looking forward to it!
