### ISSUE TITLE
Question on momentum

### ISSUE THREAD

**Issue by ShangxuanWu** [libuyu/GHM_Detection#9]
Hi Buyu,

Thanks for your good paper! I am re-writing your code into a tensorflow version and adapt it to RetinaNet. Yet I found that the vanilla GHM-R loss (no momentum) is converging much slower than smooth L1 loss in my experiments. I'm wondering if you have experiment on momentum parameters and do they affect the results a lot?

Shangxuan

**Comment by libuyu** [comment]
@ShangxuanWu You can refer to this https://github.com/libuyu/GHM_Detection/issues/6. Sorry for the late reply. And if you want to apply it in other frameworks like SSD, maybe you need to change the /mu to adapt to the new distribution.

**Comment by ShangxuanWu** [comment]
Hi @libuyu , I made it work using momentum 0.5 and mu 0.02 in large datasets, in my tensorflow implementation. Thanks!

**Comment by libuyu** [comment]
Good job! And thank you for your efforts!

**Comment by tenggyut** [comment]
@ShangxuanWu Any chance sharing the tf-version of the GHM loss? Would be very appreciate !

**Comment by congxin513** [comment]
@ShangxuanWu  It doesn't work when I add ghmc_loss and ghmr_loss to other networks. The loss value does not decrease after multiple iterations, and the network cannot learn anything from it. May I get your WeChat or email? I want to ask you about it.
